/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author USUARIO
 */
public class ViewCompras extends javax.swing.JPanel {

    /**
     * Creates new form ViewCompras
     */
    public ViewCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_compra_id = new javax.swing.JLabel();
        jtf_compra_id = new javax.swing.JTextField();
        jl_sucursal = new javax.swing.JLabel();
        jtf_sucursal_id = new javax.swing.JTextField();
        jtf_sucursal_calle = new javax.swing.JTextField();
        jl_fecha = new javax.swing.JLabel();
        jtf_fecha = new javax.swing.JTextField();
        jl_usuario = new javax.swing.JLabel();
        jtf_compra_id4 = new javax.swing.JTextField();
        jtf_usuario_nombre = new javax.swing.JTextField();
        jl_buscar = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();
        jl_cantidad = new javax.swing.JLabel();
        jsp_cantidad = new javax.swing.JSpinner();
        jl_precio_compra = new javax.swing.JLabel();
        jtf_precio_compra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_productos = new javax.swing.JTable();
        jb_agregar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_detalle_compra = new javax.swing.JTable();
        jb_finalizar = new javax.swing.JButton();
        jl_subtotal = new javax.swing.JLabel();
        jtf_subtotal = new javax.swing.JTextField();
        jtf_iva = new javax.swing.JTextField();
        jl_iva = new javax.swing.JLabel();
        jtf_total = new javax.swing.JTextField();
        jl_total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jl_logoempresa = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(48, 131, 175));

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(1104, 545));

        jl_compra_id.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_compra_id.setText("COMPRA NO.");

        jtf_compra_id.setBackground(new java.awt.Color(244, 244, 244));
        jtf_compra_id.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jl_sucursal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_sucursal.setText("SUCURSAL:");

        jtf_sucursal_id.setBackground(new java.awt.Color(244, 244, 244));
        jtf_sucursal_id.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_sucursal_calle.setBackground(new java.awt.Color(244, 244, 244));
        jtf_sucursal_calle.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jl_fecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_fecha.setText("FECHA:");

        jtf_fecha.setBackground(new java.awt.Color(244, 244, 244));
        jtf_fecha.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jl_usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_usuario.setText("USUARIO:");

        jtf_compra_id4.setBackground(new java.awt.Color(244, 244, 244));
        jtf_compra_id4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_usuario_nombre.setBackground(new java.awt.Color(244, 244, 244));
        jtf_usuario_nombre.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jl_buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_buscar.setText("BUSCAR PRODUCTO:");

        jtf_buscar.setBackground(new java.awt.Color(244, 244, 244));
        jtf_buscar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jl_cantidad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_cantidad.setText("CANTIDAD:");

        jl_precio_compra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_precio_compra.setText("PRECIO DE COMPRA:");

        jtf_precio_compra.setBackground(new java.awt.Color(244, 244, 244));
        jtf_precio_compra.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtb_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtb_productos);

        jb_agregar.setBackground(new java.awt.Color(48, 131, 175));
        jb_agregar.setFont(new java.awt.Font("Arial", 3, 17)); // NOI18N
        jb_agregar.setForeground(new java.awt.Color(255, 255, 255));
        jb_agregar.setText("Agregar");
        jb_agregar.setBorder(null);
        jb_agregar.setContentAreaFilled(false);
        jb_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_agregar.setOpaque(true);

        jb_eliminar.setBackground(new java.awt.Color(48, 131, 175));
        jb_eliminar.setFont(new java.awt.Font("Arial", 3, 17)); // NOI18N
        jb_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jb_eliminar.setText("Eliminar");
        jb_eliminar.setBorder(null);
        jb_eliminar.setContentAreaFilled(false);
        jb_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_eliminar.setOpaque(true);

        jtb_detalle_compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtb_detalle_compra);

        jb_finalizar.setBackground(new java.awt.Color(48, 131, 175));
        jb_finalizar.setFont(new java.awt.Font("Arial", 3, 17)); // NOI18N
        jb_finalizar.setForeground(new java.awt.Color(255, 255, 255));
        jb_finalizar.setText("Finalizar");
        jb_finalizar.setBorder(null);
        jb_finalizar.setContentAreaFilled(false);
        jb_finalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_finalizar.setOpaque(true);

        jl_subtotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_subtotal.setText("SUBTOTAL:");

        jtf_subtotal.setBackground(new java.awt.Color(244, 244, 244));
        jtf_subtotal.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jtf_iva.setBackground(new java.awt.Color(244, 244, 244));
        jtf_iva.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jl_iva.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_iva.setText("IVA:");

        jtf_total.setBackground(new java.awt.Color(244, 244, 244));
        jtf_total.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jl_total.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_total.setText("TOTAL:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar - copia.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo_documento.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_precio_compra)
                            .addComponent(jl_cantidad)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jl_buscar)
                                .addComponent(jl_usuario)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jl_compra_id)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtf_compra_id, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtf_buscar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtf_usuario_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtf_compra_id4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtf_precio_compra, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jsp_cantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(235, 235, 235))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_sucursal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_sucursal_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtf_sucursal_id, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_fecha)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb_finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(19, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jl_iva)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtf_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jl_subtotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jl_total)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jtf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_compra_id)
                            .addComponent(jtf_compra_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_sucursal)
                            .addComponent(jtf_sucursal_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_sucursal_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_fecha)
                            .addComponent(jtf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_usuario)
                            .addComponent(jtf_compra_id4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_usuario_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jl_buscar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_cantidad)
                            .addComponent(jsp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_precio_compra)
                    .addComponent(jtf_precio_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_subtotal)
                    .addComponent(jtf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_total)
                    .addComponent(jtf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_iva)
                    .addComponent(jtf_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jl_logoempresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/debug_ware (1).png"))); // NOI18N

        jl_titulo.setFont(new java.awt.Font("Arial", 1, 33)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jl_titulo.setText("COMPRAS");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goods.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_logoempresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_titulo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_logoempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_compra_id6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_compra_id6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_compra_id6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jb_agregar;
    public javax.swing.JButton jb_eliminar;
    public javax.swing.JButton jb_finalizar;
    public javax.swing.JLabel jl_buscar;
    public javax.swing.JLabel jl_cantidad;
    public javax.swing.JLabel jl_compra_id;
    public javax.swing.JLabel jl_fecha;
    public javax.swing.JLabel jl_iva;
    private javax.swing.JLabel jl_logoempresa;
    public javax.swing.JLabel jl_precio_compra;
    public javax.swing.JLabel jl_subtotal;
    public javax.swing.JLabel jl_sucursal;
    private javax.swing.JLabel jl_titulo;
    public javax.swing.JLabel jl_total;
    public javax.swing.JLabel jl_usuario;
    private javax.swing.JSpinner jsp_cantidad;
    public javax.swing.JTable jtb_detalle_compra;
    public javax.swing.JTable jtb_productos;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_compra_id;
    public javax.swing.JTextField jtf_compra_id4;
    public javax.swing.JTextField jtf_fecha;
    public javax.swing.JTextField jtf_iva;
    public javax.swing.JTextField jtf_precio_compra;
    public javax.swing.JTextField jtf_subtotal;
    public javax.swing.JTextField jtf_sucursal_calle;
    public javax.swing.JTextField jtf_sucursal_id;
    public javax.swing.JTextField jtf_total;
    public javax.swing.JTextField jtf_usuario_nombre;
    // End of variables declaration//GEN-END:variables
}
